const searchedImage="https://images.unsplash.com/photo-1633933703119-5d25460ad829?auto=format&fit=crop&w=1200&q=82";
const tracks=[
{id:"afterglow",title:"Afterglow",artist:"Lunara",album:"Fading Light",year:2026,genre:"Electronic",duration:228,art:"assets/afterglow.png",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",desc:"A slow-burning electronic reverie, built from glassy synths, distant percussion and the warm pulse that remains when the night starts to fade."},
{id:"neon-drift",title:"Neon Drift",artist:"Sidd",album:"Night Signal",year:2026,genre:"Synthwave",duration:262,art:searchedImage,audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",desc:"A late-night glide through saturated streets, taut drums and luminous chords."},
{id:"velvet-sky",title:"Velvet Sky",artist:"Mira Vale",album:"Soft Focus",year:2025,genre:"Dream Pop",duration:214,art:"https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=82",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",desc:"Dream-pop weightlessness with a soft vocal haze and a midnight-blue heart."},
{id:"parallel-lines",title:"Parallel Lines",artist:"North Arcade",album:"Vector",year:2025,genre:"Indie Electronic",duration:196,art:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=82",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",desc:"Clean guitars and restless circuitry moving side by side, never quite touching."},
{id:"moonwater",title:"Moonwater",artist:"Eira",album:"Still Tides",year:2026,genre:"Ambient",duration:289,art:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=82",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",desc:"An ambient wash of slow piano, breath and silver-blue space."},
{id:"signal-bloom",title:"Signal Bloom",artist:"Arc Static",album:"Open Circuit",year:2024,genre:"Alternative",duration:241,art:"https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=900&q=82",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",desc:"A bright collision of distorted bass, fractured rhythm and melodic release."},
{id:"slow-motion",title:"Slow Motion",artist:"Kei Rose",album:"Silver Hours",year:2025,genre:"R&B",duration:205,art:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=900&q=82",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",desc:"Minimal nocturnal R&B with close vocals and room for every note to linger."},
{id:"quiet-geometry",title:"Quiet Geometry",artist:"Aster House",album:"Rooms",year:2024,genre:"Modern Classical",duration:233,art:"https://images.unsplash.com/photo-1494232410401-ad00d5433cfa?auto=format&fit=crop&w=900&q=82",audio:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",desc:"Piano, cello and subtle tape noise arranged in patient, architectural forms."}];
const state={route:"home",current:0,playing:false,shuffle:false,repeat:false,favs:new Set(JSON.parse(localStorage.getItem("cs-favs")||'["afterglow","moonwater"]')),recent:JSON.parse(localStorage.getItem("cs-recent")||'["afterglow","neon-drift","velvet-sky","parallel-lines"]')};
const $=s=>document.querySelector(s), main=$("#main"), audio=$("#audio"), progress=$("#progress"), volume=$("#volume"), queue=$("#queue"), sidebar=$("#sidebar"), scrim=$("#scrim");let toastTimer;
const fmt=s=>`${Math.floor((s||0)/60)}:${String(Math.floor((s||0)%60)).padStart(2,"0")}`,byId=id=>tracks.find(t=>t.id===id),icons=()=>window.lucide&&lucide.createIcons({attrs:{"stroke-width":1.8}});
const card=t=>`<button class="card" data-open="${t.id}" aria-label="Open ${t.title} by ${t.artist}"><span class="art"><img src="${t.art}" alt="${t.title} artwork" loading="lazy"><span class="cardplay" data-play="${t.id}"><i data-lucide="play"></i></span></span><h3>${t.title}</h3><p>${t.artist}</p></button>`;
const rows=list=>`<div class="tracks">${list.map(t=>`<div class="track ${tracks[state.current].id===t.id?"current":""}" data-open="${t.id}"><img src="${t.art}" alt="" loading="lazy"><span class="meta"><strong>${t.title}</strong><small>${t.artist}</small></span><span class="album">${t.album}</span><button class="heart ${state.favs.has(t.id)?"liked":""}" data-fav="${t.id}" title="Favourite" aria-label="Favourite ${t.title}"><i data-lucide="heart"></i></button><span class="time">${fmt(t.duration)}</span></div>`).join("")}</div>`;
const section=(title,list,route)=>`<section class="section"><div class="sectionhead"><h2>${title}</h2>${route?`<button data-route="${route}">See all</button>`:""}</div>${Array.isArray(list)?`<div class="grid">${list.map(card).join("")}</div>`:list}</section>`;
function home(){return `<div class="wrap"><section class="hero"><div><p class="eyebrow">Curated for deep listening</p><h1>Feel every <span>frequency.</span></h1><p>A focused home for the music you love—beautifully organized, effortlessly played, and always one tap away.</p><div class="buttons"><button class="primary" data-play="afterglow"><i data-lucide="play"></i>Play Afterglow</button><button class="secondary" data-route="browse"><i data-lucide="layout-grid"></i>Explore music</button></div></div><div class="heroart"><img src="assets/afterglow.png" alt="Abstract luminous glass orb album artwork"></div></section>${section("Recently Played",state.recent.slice(0,5).map(byId),"recent")}${section("Favourites",[...state.favs].slice(0,5).map(byId),"favorites")}${section("Made for Sidd",rows(tracks.slice(2,7)))}</div>`}
function library(title,desc,list){return `<div class="wrap"><header class="pagehead"><div><p class="eyebrow">Your Library</p><h1>${title}</h1></div>${list.length?`<button class="primary" data-play="${list[0].id}"><i data-lucide="play"></i>Play all</button>`:""}</header><p class="intro">${desc}</p>${list.length?`<div class="grid">${list.map(card).join("")}</div>${section("All tracks",rows(list))}`:empty("Nothing here yet","Tap the heart beside a track and it will appear here.")}</div>`}
function browse(){return `<div class="wrap"><header class="pagehead"><div><p class="eyebrow">New sounds, no noise</p><h1>Browse</h1></div><button class="primary" data-shuffle><i data-lucide="shuffle"></i>Shuffle all</button></header><p class="intro">A hand-picked mix of late-night electronics, quiet pop, ambient textures and modern soul.</p><div class="grid">${tracks.map(card).join("")}</div>${section("All tracks",rows(tracks))}</div>`}
function radio(){let s=[["Night Signal","Electronic · Live",searchedImage,"neon-drift"],["Soft Focus","Dream Pop · Curated",tracks[2].art,"velvet-sky"],["Still Tides","Ambient · Nonstop",tracks[4].art,"moonwater"]];return `<div class="wrap"><header class="pagehead"><div><p class="eyebrow">Always on</p><h1>Radio</h1></div></header><p class="intro">Three focused stations, tuned for making, moving and switching off.</p><div class="stations">${s.map(x=>`<button class="station" data-play="${x[3]}" style="background-image:url('${x[2]}')"><p>${x[1]}</p><h3>${x[0]}</h3></button>`).join("")}</div>${section("Featured on radio",rows([tracks[1],tracks[2],tracks[4],tracks[5]]))}</div>`}
function detail(t){return `<div class="wrap"><button class="secondary" data-route="home"><i data-lucide="arrow-left"></i>Back</button><section class="detailhero"><img class="detailart" src="${t.art}" alt="${t.title} artwork"><div class="detail"><p class="eyebrow">Single</p><h1>${t.title}</h1><p class="artist">${t.artist}</p><p class="facts">${t.album} · ${t.year} · ${t.genre} · ${fmt(t.duration)}</p><div class="buttons"><button class="primary" data-play="${t.id}"><i data-lucide="play"></i>Play</button><button class="secondary ${state.favs.has(t.id)?"isactive":""}" data-fav="${t.id}"><i data-lucide="heart"></i>${state.favs.has(t.id)?"Favourited":"Favourite"}</button><button class="icon" data-toast="Added to your queue" title="Add to queue"><i data-lucide="list-plus"></i></button><button class="icon" data-toast="Link copied" title="Share"><i data-lucide="share-2"></i></button></div><p class="description">${t.desc}</p></div></section>${section("More like this",tracks.filter(x=>x.id!==t.id).slice(0,5))}</div>`}
const empty=(title,copy)=>`<div class="empty"><div><i data-lucide="music-2"></i><br><strong>${title}</strong><p>${copy}</p></div></div>`;
function searchPage(q){let r=tracks.filter(t=>`${t.title} ${t.artist} ${t.album} ${t.genre}`.toLowerCase().includes(q.toLowerCase()));return `<div class="wrap"><header class="pagehead"><div><p class="eyebrow">Search results</p><h1>“${q}”</h1></div></header><p class="intro">${r.length} ${r.length===1?"track":"tracks"} found.</p>${r.length?`<div class="grid">${r.map(card).join("")}</div>${section("Matches",rows(r))}`:empty("No matches","Try a title, artist, album or genre.")}</div>`}
function render(route=state.route,payload){state.route=route;if(route==="track")main.innerHTML=detail(byId(payload));else if(route==="browse")main.innerHTML=browse();else if(route==="radio")main.innerHTML=radio();else if(route==="favorites")main.innerHTML=library("Favourites","The songs you never want to lose.",[...state.favs].map(byId));else if(route==="recent")main.innerHTML=library("Recently Played","Pick up exactly where the mood left you.",state.recent.map(byId));else if(route==="search")main.innerHTML=searchPage(payload);else main.innerHTML=home();document.querySelectorAll("[data-route]").forEach(b=>b.classList.toggle("active",b.dataset.route===route));window.scrollTo({top:0,behavior:"smooth"});icons()}
function save(){localStorage.setItem("cs-favs",JSON.stringify([...state.favs]));localStorage.setItem("cs-recent",JSON.stringify(state.recent))}function toast(m){$("#toast").textContent=m;$("#toast").classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function setTrack(id,auto=true){let i=tracks.findIndex(t=>t.id===id);if(i<0)return;state.current=i;let t=tracks[i];audio.src=t.audio;$("#pArt").src=t.art;$("#pTitle").textContent=t.title;$("#pArtist").textContent=t.artist;$("#duration").textContent=fmt(t.duration);$("#favCurrent").classList.toggle("on",state.favs.has(id));$("#openCurrent").dataset.open=id;state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);save();renderQueue();if(auto)playAudio()}
async function playAudio(){try{await audio.play();state.playing=true;updatePlay()}catch{state.playing=false;updatePlay();toast("Tap play once more to start audio")}}function pause(){audio.pause();state.playing=false;updatePlay()}function updatePlay(){$("#play").innerHTML=`<i data-lucide="${state.playing?"pause":"play"}"></i>`;$("#play").title=state.playing?"Pause":"Play";icons()}
function next(d=1){let i;if(state.shuffle){do i=Math.floor(Math.random()*tracks.length);while(i===state.current&&tracks.length>1)}else i=(state.current+d+tracks.length)%tracks.length;setTrack(tracks[i].id)}
function fav(id){state.favs.has(id)?(state.favs.delete(id),toast("Removed from favourites")):(state.favs.add(id),toast("Added to favourites"));save();$("#favCurrent").classList.toggle("on",state.favs.has(tracks[state.current].id));if(["favorites","home"].includes(state.route))render(state.route);else if(state.route==="track")render("track",id)}
function renderQueue(){$("#queueList").innerHTML=tracks.map((t,i)=>`<button class="qitem ${i===state.current?"active":""}" data-play="${t.id}"><img src="${t.art}" alt=""><span><strong>${t.title}</strong><small>${t.artist}</small></span><small>${fmt(t.duration)}</small></button>`).join("")}
function close(){queue.classList.remove("open");sidebar.classList.remove("open");scrim.classList.remove("open")}
document.addEventListener("click",e=>{let r=e.target.closest("[data-route]");if(r){render(r.dataset.route);close();return}let p=e.target.closest("[data-play]");if(p){e.preventDefault();e.stopPropagation();setTrack(p.dataset.play);close();return}let o=e.target.closest("[data-open]");if(o){render("track",o.dataset.open);return}let f=e.target.closest("[data-fav]");if(f){e.preventDefault();e.stopPropagation();fav(f.dataset.fav);return}let t=e.target.closest("[data-toast]");if(t)toast(t.dataset.toast);if(e.target.closest("[data-shuffle]")){state.shuffle=true;$("#shuffle").classList.add("on");next()}});
$("#play").onclick=()=>!audio.src?setTrack(tracks[state.current].id):state.playing?pause():playAudio();$("#next").onclick=()=>next();$("#prev").onclick=()=>audio.currentTime>4?audio.currentTime=0:next(-1);$("#shuffle").onclick=e=>{state.shuffle=!state.shuffle;e.currentTarget.classList.toggle("on",state.shuffle);toast(`Shuffle ${state.shuffle?"on":"off"}`)};$("#repeat").onclick=e=>{state.repeat=!state.repeat;audio.loop=state.repeat;e.currentTarget.classList.toggle("on",state.repeat);toast(`Repeat ${state.repeat?"on":"off"}`)};$("#favCurrent").onclick=()=>fav(tracks[state.current].id);$("#queueBtn").onclick=()=>{queue.classList.add("open");scrim.classList.add("open")};$("#closeQueue").onclick=close;$("#menu").onclick=()=>{sidebar.classList.add("open");scrim.classList.add("open")};$("#closeMenu").onclick=close;scrim.onclick=close;
$(".avatar").onclick=()=>window.innerWidth<=580?$(".search").classList.toggle("open"):toast("Profile synced locally");$("#search").oninput=e=>{let q=e.target.value.trim();q?render("search",q):render("home")};document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$(".search").classList.add("open");$("#search").focus()}if(e.code==="Space"&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();state.playing?pause():playAudio()}if(e.key==="Escape")close()});
audio.ontimeupdate=()=>{let d=audio.duration||tracks[state.current].duration,v=d?audio.currentTime/d*100:0;progress.value=v;progress.style.setProperty("--progress",`${v}%`);$("#current").textContent=fmt(audio.currentTime);$("#duration").textContent=fmt(d)};audio.onended=()=>!state.repeat&&next();audio.onplay=()=>{state.playing=true;updatePlay()};audio.onpause=()=>{state.playing=false;updatePlay()};progress.oninput=e=>audio.currentTime=Number(e.target.value)/100*(audio.duration||tracks[state.current].duration);volume.oninput=e=>{audio.volume=Number(e.target.value)/100;e.target.style.setProperty("--progress",`${e.target.value}%`)};audio.volume=.72;setTrack("afterglow",false);render("home");renderQueue();icons();
